Repository Limit-Theory-Redux/ltheory, pull requests merged in 2023-03, with the labels that each got.

#38 Flat/framework
  README.md
  docs/GameControlKeys.txt
  script/Config/App.lua
  script/GameObjects/Actions/DockAt.lua
  script/GameObjects/Actions/MineAt.lua
  script/GameObjects/Actions/MoveTo.lua
  script/GameObjects/Actions/Think.lua
  script/GameObjects/Components/Economy/Economy.lua
  script/GameObjects/Components/Economy/Market.lua
  script/GameObjects/Components/NPC/Actions.lua
  script/GameObjects/Components/NPC/Trader.lua
  script/GameObjects/Components/Object/Factory.lua
  script/GameObjects/Components/Ship/ThrustController.lua
  script/GameObjects/Entities/Player.lua
  script/GameObjects/Entities/Ship/Turret.lua
  script/GameObjects/Entities/Test/Content.lua
  script/GameObjects/Entities/Test/System.lua
  script/GameObjects/Jobs/Mine.lua
  script/GameObjects/Jobs/Transport.lua
  script/States/App/LTheoryRedux.lua
  script/States/App/TestEcon.lua
  script/States/ApplicationBindings.lua
  script/Systems/CommandView/SystemMap.lua
  script/Systems/Controls/Bindings/ShipBindings.lua
  script/Systems/Overlay/HUD.lua
Labels: enhancement

#39 Add support for draggable/resizable game window [PHX REBUILD REQUIRED]
  .gitignore
  libphx/include/Button.h
  libphx/script/ffi/Button.lua
  libphx/src/Button.cpp
  libphx/src/Input.cpp
  script/States/Application.lua
Labels: bug

#45 Numerous minor fixes
  docs/GameControlKeys.txt
  res/images/LTR_logo2.png
  res/shader/fragment/ui/triangle - Copy.glsl
  script/Config/App.lua
  script/Config/Local.lua
  script/GameObjects/Actions/MineAt.lua
  script/GameObjects/Components/Core/Attackable.lua
  script/GameObjects/Components/Core/Health.lua
  script/GameObjects/Components/Core/Minable.lua
  script/GameObjects/Components/Core/Trackable.lua
  script/GameObjects/Components/Economy/Economy.lua
  script/GameObjects/Components/Economy/Market.lua
  script/GameObjects/Components/NPC/Actions.lua
  script/GameObjects/Components/NPC/Dispositions.lua
  script/GameObjects/Components/NPC/Trader.lua
  script/GameObjects/Components/Object/Factory.lua
  script/GameObjects/Components/Object/Yield.lua
  script/GameObjects/Entities/Effects/Pulse.lua
  script/GameObjects/Entities/Ship/Ship.lua
  script/GameObjects/Entities/Ship/ShipInvis.lua
  script/GameObjects/Entities/Ship/Turret.lua
  script/GameObjects/Entities/Test/System.lua
  script/GameObjects/Jobs/Mine.lua
  script/GameObjects/Jobs/Transport.lua
  script/Render/Renderer.lua
  script/States/App/LTheory.lua
  script/States/App/LTheoryRedux.lua
  script/States/App/TestEcon.lua
  script/States/App/TestIcon.lua
  script/States/Application.lua
  script/States/ApplicationBindings.lua
  script/Systems/Controls/Bindings/ShipBindings.lua
  script/Systems/Controls/Controls/MasterControl.lua
  script/Systems/Overlay/HUD.lua
  script/UI/DrawEx.lua
Labels: bug, enhancement, economy
