Repository Limit-Theory-Redux/ltheory, pull requests merged in 2023-04, with the labels that each got.

#46 Player ship's thrusters add dynamic world lighting
  res/shader/vertex/billboard/axisInvert.glsl
  script/Config/App.lua
  script/Config/Local.lua
  script/GameObjects/Entities/Effects/Pulse.lua
  script/GameObjects/Entities/Objects/Station.lua
  script/GameObjects/Entities/Ship/Thruster.lua
  script/GameObjects/Entities/Test/System.lua
  script/States/App/LTheoryRedux.lua
  script/States/ApplicationBindings.lua
  script/Systems/Overlay/GameView.lua
Labels: bug, enhancement, cleanup

#48 Dynamic pulse lights, numerous station improvements
  docs/GameControlKeys.txt
  res/shader/vertex/billboard/axisInvert.glsl
  script/Config/App.lua
  script/Config/Local.lua
  script/GameObjects/Action.lua
  script/GameObjects/Actions/Attack.lua
  script/GameObjects/Actions/DockAt.lua
  script/GameObjects/Actions/MineAt.lua
  script/GameObjects/Actions/Think.lua
  script/GameObjects/Components/Core/Health.lua
  script/GameObjects/Components/Economy/Economy.lua
  script/GameObjects/Components/Economy/Market.lua
  script/GameObjects/Components/NPC/Actions.lua
  script/GameObjects/Components/NPC/Trader.lua
  script/GameObjects/Components/Object/Factory.lua
  script/GameObjects/Components/Other/Dockable.lua
  script/GameObjects/Components/Other/Light.lua
  script/GameObjects/Components/Other/Projectiles.lua
  script/GameObjects/Entities/Effects/Pulse.lua
  script/GameObjects/Entities/Objects/Projectile.lua
  script/GameObjects/Entities/Objects/Station.lua
  script/GameObjects/Entities/Ship/Ship.lua
  script/GameObjects/Entities/Ship/Thruster.lua
  script/GameObjects/Entities/Ship/Turret.lua
  script/GameObjects/Entities/Test/System.lua
  script/GameObjects/Entity.lua
  script/GameObjects/Jobs/Mine.lua
  script/GameObjects/Jobs/Transport.lua
  script/States/App/LTheory.lua
  script/States/App/LTheoryRedux.lua
  script/States/App/TestEcon.lua
  script/Systems/CommandView/SystemMap.lua
  script/Systems/Overlay/GameView.lua
  script/Systems/Overlay/HUD.lua
Labels: bug, enhancement, question, graphics, cleanup

#58 [PHX] Set custom cursor from image, per-window
  libphx/include/Tex2D.h
  libphx/include/Window.h
  libphx/script/ffi/Window.lua
  libphx/src/Tex2D.cpp
  libphx/src/TexCube.cpp
  libphx/src/Window.cpp
  res/tex2d/cursor/simple_cursor.png
  script/States/Application.lua
Labels: enhancement, graphics

#59 Enable basic overlay modes
  docs/GameControlKeys.txt
  res/shader/fragment/ui/hologram.glsl
  res/shader/fragment/ui/line.glsl
  res/shader/fragment/ui/ring.glsl
  res/tex2d/cursor/cursor1-small.png
  script/Config/App.lua
  script/Config/Local.lua
  script/GameObjects/Entities/Objects/Projectile.lua
  script/GameObjects/Entities/Ship/Turret.lua
  script/GameObjects/Entities/Test/System.lua
  script/States/App/LTheory.lua
  script/States/App/LTheoryRedux.lua
  script/States/App/TestEcon.lua
  script/States/Application.lua
  script/States/ApplicationBindings.lua
  script/Systems/CommandView/SystemMap.lua
  script/Systems/Controls/Bindings/DebugBindings.lua
  script/Systems/Controls/Bindings/ShipBindings.lua
  script/Systems/Controls/Controls/BackgroundControl.lua
  script/Systems/Controls/Controls/CommandControl.lua
  script/Systems/Controls/Controls/DebugControl.lua
  script/Systems/Controls/Controls/DockControl.lua
  script/Systems/Controls/Controls/MasterControl.lua
  script/Systems/Files/InitFiles.lua
  script/Systems/Overlay/HUD.lua
  script/UI/Bindings.lua
  script/UI/Canvas.lua
  script/UI/DrawEx.lua
  script/UI/Window.lua
  user.ini
Labels: cleanup

#64 feature(mouse): set mouse in input & window class
  libphx/include/Window.h
  libphx/script/ffi/Window.lua
  libphx/script/ffiext/Input.lua
  libphx/script/ffiext/Window.lua
  libphx/src/Window.cpp
  script/States/App/LTheoryRedux.lua
  script/States/Application.lua
Labels: enhancement, core
