Repository Limit-Theory-Redux/ltheory, pull requests merged in 2023-06, with the labels that each got.

#109 fix: quick fix for game over text
  script/States/Application.lua
Labels: bug

#116 Initial version of Sensor display
  script/Config/App.lua
  script/Enums/EmissionEnums.lua
  script/GameObjects/Elements/Core/ComponentMgr.lua
  script/GameObjects/Elements/Core/Damage.lua
  script/GameObjects/Elements/Economy/Content.lua
  script/States/App/LTheory.lua
  script/States/App/LTheoryRedux.lua
  script/States/App/Quickstart.lua
  script/Systems/Overlay/HUD.lua
  script/Systems/Universe/UniverseEconomy.lua
Labels: enhancement

#121 Check activeControlSet not nil before access.
  script/Systems/Controls/Controls/MasterControl.lua
Labels: good first issue

#122 tweak: default music volume
  script/Config/App.lua
Labels: enhancement

#125 Don't display sensor activity when game is paused
  script/Config/App.lua
  script/GameObjects/Elements/Core/ComponentMgr.lua
  script/GameObjects/Elements/NPC/Trader.lua
  script/GameObjects/Entities/Ship/Bay.lua
  script/GameObjects/Entities/Ship/Drone.lua
  script/GameObjects/Entities/Ship/Turret.lua
  script/GameObjects/Jobs/Mine.lua
  script/GameObjects/Jobs/Transport.lua
  script/States/App/LTheoryRedux.lua
  script/States/App/Tests/AudioTest.lua
  script/States/App/Tests/TestEcon.lua
  script/States/Application.lua
  script/Systems/Overlay/DebugWindow.lua
  script/Systems/Overlay/HUD.lua
  script/Systems/SFX/MusicPlayer.lua
  script/Systems/Universe/Universe.lua
Labels: bug, enhancement

#127 Fixed Lua diagnostic nits
  script/Render/Renderer.lua
  script/States/App/Quickstart.lua
  script/Systems/Controls/Controls/CommandControl.lua
  script/Systems/Gen/ShipFighter.lua
Labels: cleanup

#126 Remove limiting "/" prefix in IDE section of .gitignore.
  .gitignore
Labels: cleanup
