Repository Limit-Theory-Redux/ltheory, pull requests merged in 2023-05, with the labels that each got.

#70 Settings / Energy Capacitor / Overcharge
  script/Config/App.lua
  script/GameObjects/Actions/Attack.lua
  script/GameObjects/Components/Ship/Capacitor.lua
  script/GameObjects/Entities/Ship/Turret.lua
  script/States/App/LTheoryRedux.lua
  script/States/Application.lua
  script/Systems/Controls/Controls/DockControl.lua
  script/Systems/Menus/MainMenu.lua
  script/Systems/Overlay/HUD.lua
  script/UI/DrawEx.lua
Labels: enhancement

#72 Universe Class, GameStates and more
  .vscode/settings.json
  script/Config/App.lua
  script/Config/Local.lua
  script/Enums/GameStates.lua
  script/GameObjects/Action.lua
  script/GameObjects/Actions/DockAt.lua
  script/GameObjects/Actions/MineAt.lua
  script/GameObjects/Actions/MoveTo.lua
  script/GameObjects/Actions/Think.lua
  script/GameObjects/Components/Core/Health.lua
  script/GameObjects/Components/Economy/Economy.lua
  script/GameObjects/Components/Economy/Market.lua
  script/GameObjects/Components/NPC/Actions.lua
  script/GameObjects/Components/NPC/Trader.lua
  script/GameObjects/Components/Object/Factory.lua
  script/GameObjects/Components/Object/Yield.lua
  script/GameObjects/Components/Other/Light.lua
  script/GameObjects/Entities/Objects/Projectile.lua
  script/GameObjects/Entities/Ship/Ship.lua
  script/GameObjects/Entities/Ship/ShipType.lua
  script/GameObjects/Entities/Ship/Thruster.lua
  script/GameObjects/Entities/Ship/Turret.lua
  script/GameObjects/Entities/Test/System.lua
  script/GameObjects/Jobs/Mine.lua
  script/GameObjects/Jobs/Transport.lua
  script/Init.lua
  script/Main.lua
  script/States/App/LTheory.lua
  script/States/App/LTheoryRedux.lua
  script/States/App/TestEcon.lua
  script/States/Application.lua
  script/Systems/Camera/Camera.lua
  script/Systems/CommandView/SystemMap.lua
  script/Systems/Controls/Bindings/ShipBindings.lua
  script/Systems/Controls/Controls/DockControl.lua
  script/Systems/Controls/Controls/MasterControl.lua
  script/Systems/Files/InitFiles.lua
  script/Systems/Menus/MainMenu.lua
  script/Systems/Overlay/GameView.lua
  script/Systems/Overlay/HUD.lua
  script/Systems/SFX/MusicPlayer.lua
  script/Systems/Universe/Universe.lua
  script/Systems/Universe/UniverseEconomy.lua
  script/Types/GameState.lua
Labels: enhancement, economy, cleanup

#75 Minor updates
  script/Config/App.lua
  script/Core/Structures/Settings.lua
  script/GameObjects/Entities/Test/System.lua
  script/States/App/LTheoryRedux.lua
  script/Systems/Camera/CameraChase.lua
  script/Systems/CommandView/SystemMap.lua
  script/Systems/Menus/MainMenu.lua
  script/Systems/Overlay/GameView.lua
  script/Systems/Overlay/HUD.lua
  script/Types/GameState.lua
Labels: bug, enhancement

#73 feature(camera): minor improvements
  script/Systems/Controls/Controls/DockControl.lua
Labels: enhancement

#82 Flat/framework
  script/GameObjects/Entities/Ship/ShipInvis.lua
  script/GameObjects/Entities/Ship/ShipType.lua
  script/GameObjects/Entities/Test/System.lua
  script/States/App/LTheoryRedux.lua
  script/States/Application.lua
  script/Systems/Gen/Ship.lua
  script/Systems/Gen/ShipInvisible.lua
Labels: bug, enhancement

#84 feature(shader): add weak nebula shader
  res/shader/fragment/gen/nebula4_weak.glsl
Labels: enhancement, graphics

#86 Rewrite the signal handler code using safe Rust HashMaps
  libphx/src/Lua.rs
  libphx/src/Profiler.rs
  libphx/src/Signal.rs
Labels: bug, core
